// ===== RETRO CRICKET — static data: teams, squads, free agents, media =====
// Player row: [name, role(BAT/BWL/AR/WK), batting 1-10, bowling 1-10, age]

const TEAMS = [
  {id:"MI",  name:"Mumbai Indians",            c1:"#0a4fa0", c2:"#c9a23f"},
  {id:"CSK", name:"Chennai Super Kings",       c1:"#caa008", c2:"#1b3a8c"},
  {id:"RCB", name:"Royal Challengers Bengaluru",c1:"#c8102e", c2:"#caa341"},
  {id:"KKR", name:"Kolkata Knight Riders",     c1:"#4b2a82", c2:"#caa341"},
  {id:"SRH", name:"Sunrisers Hyderabad",       c1:"#e85d04", c2:"#222222"},
  {id:"DC",  name:"Delhi Capitals",            c1:"#2a3b8f", c2:"#d11f2f"},
  {id:"PBKS",name:"Punjab Kings",              c1:"#d11f2f", c2:"#c0c0c0"},
  {id:"RR",  name:"Rajasthan Royals",          c1:"#e6189b", c2:"#1f3aa8"},
  {id:"GT",  name:"Gujarat Titans",            c1:"#1c2640", c2:"#c9a23f"},
  {id:"LSG", name:"Lucknow Super Giants",      c1:"#0aa7c2", c2:"#f08018"},
];

const SQUADS = {
  MI:[
    ["Rohit Sharma","BAT",9,1,38],
    ["Suryakumar Yadav","BAT",9.5,1,34],
    ["Tilak Varma","BAT",8.5,2,22],
    ["Will Jacks","AR",7.5,6,26],
    ["Ryan Rickelton","WK",7.5,1,28],
    ["Naman Dhir","AR",6.5,5,25],
    ["Hardik Pandya","AR",8.5,8,31],
    ["Mitchell Santner","BWL",4,8,33],
    ["Deepak Chahar","BWL",3,7.5,32],
    ["Trent Boult","BWL",2,9,35],
    ["Jasprit Bumrah","BWL",2,10,31],
    ["Karn Sharma","BWL",2,6.5,37],
    ["Reece Topley","BWL",1,7,31],
  ],
  CSK:[
    ["Ruturaj Gaikwad","BAT",9,1,28],
    ["Rachin Ravindra","AR",8,6,25],
    ["Devon Conway","BAT",8.5,1,33],
    ["Shivam Dube","AR",8,5,31],
    ["Rahul Tripathi","BAT",7,1,34],
    ["MS Dhoni","WK",7.5,1,43],
    ["Ravindra Jadeja","AR",7.5,8.5,36],
    ["Sam Curran","AR",7,7.5,26],
    ["R Ashwin","BWL",4,8,38],
    ["Noor Ahmad","BWL",1,8.5,20],
    ["Matheesha Pathirana","BWL",1,9,22],
    ["Khaleel Ahmed","BWL",1,7.5,27],
    ["Deepak Hooda","AR",6.5,4,30],
  ],
  RCB:[
    ["Virat Kohli","BAT",9.5,1,37],
    ["Phil Salt","WK",8.5,1,28],
    ["Rajat Patidar","BAT",8.5,1,31],
    ["Devdutt Padikkal","BAT",7,1,24],
    ["Liam Livingstone","AR",8,5.5,31],
    ["Tim David","BAT",8,1,29],
    ["Jitesh Sharma","WK",7,1,31],
    ["Krunal Pandya","AR",6.5,7.5,34],
    ["Romario Shepherd","AR",6.5,6.5,30],
    ["Bhuvneshwar Kumar","BWL",3,8,35],
    ["Josh Hazlewood","BWL",1,9,34],
    ["Yash Dayal","BWL",1,7,27],
    ["Suyash Sharma","BWL",1,7,22],
  ],
  KKR:[
    ["Quinton de Kock","WK",8.5,1,32],
    ["Rahmanullah Gurbaz","WK",7.5,1,23],
    ["Ajinkya Rahane","BAT",7,1,37],
    ["Venkatesh Iyer","AR",7.5,4,30],
    ["Rinku Singh","BAT",8.5,1,27],
    ["Angkrish Raghuvanshi","BAT",7,1,20],
    ["Andre Russell","AR",8.5,7,37],
    ["Ramandeep Singh","AR",6.5,4,28],
    ["Sunil Narine","AR",7.5,9,36],
    ["Anrich Nortje","BWL",1,8.5,31],
    ["Harshit Rana","BWL",2,7.5,23],
    ["Varun Chakravarthy","BWL",1,9,33],
    ["Vaibhav Arora","BWL",1,7,27],
  ],
  SRH:[
    ["Travis Head","BAT",9.5,2,31],
    ["Abhishek Sharma","AR",9,4,24],
    ["Ishan Kishan","WK",8,1,26],
    ["Nitish Kumar Reddy","AR",7.5,5,22],
    ["Heinrich Klaasen","WK",9.5,1,33],
    ["Aniket Verma","BAT",6.5,1,23],
    ["Abhinav Manohar","BAT",6.5,1,30],
    ["Pat Cummins","BWL",5,9,32],
    ["Harshal Patel","BWL",3,8,34],
    ["Mohammed Shami","BWL",2,8.5,34],
    ["Adam Zampa","BWL",1,7.5,33],
    ["Jaydev Unadkat","BWL",2,7,33],
    ["Zeeshan Ansari","BWL",1,6.5,25],
  ],
  DC:[
    ["KL Rahul","WK",9,1,33],
    ["Jake Fraser-McGurk","BAT",8,1,23],
    ["Faf du Plessis","BAT",8,1,40],
    ["Abishek Porel","WK",7.5,1,22],
    ["Karun Nair","BAT",7.5,1,33],
    ["Tristan Stubbs","BAT",8.5,2,24],
    ["Sameer Rizvi","BAT",6.5,1,21],
    ["Axar Patel","AR",7,8.5,31],
    ["Vipraj Nigam","AR",6,6.5,20],
    ["Mitchell Starc","BWL",2,9,35],
    ["Kuldeep Yadav","BWL",1,9,30],
    ["T Natarajan","BWL",1,8,34],
    ["Mukesh Kumar","BWL",1,7.5,31],
  ],
  PBKS:[
    ["Priyansh Arya","BAT",7.5,1,24],
    ["Prabhsimran Singh","WK",8,1,24],
    ["Shreyas Iyer","BAT",9,1,30],
    ["Josh Inglis","WK",8,1,30],
    ["Shashank Singh","BAT",7.5,2,33],
    ["Nehal Wadhera","BAT",7,1,24],
    ["Glenn Maxwell","AR",8,6,36],
    ["Marcus Stoinis","AR",7.5,6,35],
    ["Marco Jansen","BWL",4,8,25],
    ["Azmatullah Omarzai","AR",6.5,6.5,25],
    ["Arshdeep Singh","BWL",1,8.5,26],
    ["Yuzvendra Chahal","BWL",1,8.5,34],
    ["Lockie Ferguson","BWL",1,8,34],
  ],
  RR:[
    ["Yashasvi Jaiswal","BAT",9.5,1,23],
    ["Sanju Samson","WK",9,1,30],
    ["Vaibhav Suryavanshi","BAT",7.5,1,14],
    ["Riyan Parag","AR",8,4,23],
    ["Dhruv Jurel","WK",7.5,1,24],
    ["Shimron Hetmyer","BAT",8,1,28],
    ["Shubham Dubey","BAT",6.5,1,31],
    ["Wanindu Hasaranga","BWL",3,8.5,27],
    ["Jofra Archer","BWL",2,9,30],
    ["Maheesh Theekshana","BWL",1,8,24],
    ["Tushar Deshpande","BWL",1,7,30],
    ["Sandeep Sharma","BWL",1,7.5,32],
    ["Fazalhaq Farooqi","BWL",1,7.5,24],
  ],
  GT:[
    ["Shubman Gill","BAT",9.5,1,25],
    ["Jos Buttler","WK",9,1,35],
    ["Sai Sudharsan","BAT",9,1,23],
    ["Shahrukh Khan","BAT",7,1,30],
    ["Sherfane Rutherford","BAT",7.5,1,26],
    ["Rahul Tewatia","AR",7,5.5,32],
    ["Washington Sundar","AR",6.5,7,25],
    ["Rashid Khan","AR",6,9.5,26],
    ["Kagiso Rabada","BWL",2,9,30],
    ["Mohammed Siraj","BWL",1,8.5,31],
    ["Prasidh Krishna","BWL",1,8,29],
    ["R Sai Kishore","BWL",2,7.5,28],
    ["Gerald Coetzee","BWL",2,7.5,24],
  ],
  LSG:[
    ["Rishabh Pant","WK",9,1,27],
    ["Nicholas Pooran","WK",9.5,1,29],
    ["Mitchell Marsh","AR",8.5,5,33],
    ["Aiden Markram","BAT",8,4,30],
    ["David Miller","BAT",8,1,36],
    ["Ayush Badoni","BAT",7.5,2,25],
    ["Abdul Samad","BAT",7,1,23],
    ["Shardul Thakur","AR",5,7,33],
    ["Ravi Bishnoi","BWL",1,8,24],
    ["Avesh Khan","BWL",1,8,28],
    ["Mayank Yadav","BWL",1,8,23],
    ["Mohsin Khan","BWL",1,7.5,26],
    ["Akash Deep","BWL",1,7,28],
  ],
};

const FREE_AGENTS = [
  ["David Warner","BAT",8.5,1,38],
  ["Kane Williamson","BAT",8,1,35],
  ["Steve Smith","BAT",8,1,36],
  ["Jonny Bairstow","WK",8,1,35],
  ["Jason Roy","BAT",7.5,1,34],
  ["Daryl Mitchell","BAT",7.5,4,34],
  ["Finn Allen","BAT",8,1,26],
  ["Sikandar Raza","AR",7,7,39],
  ["Mustafizur Rahman","BWL",1,8,29],
  ["Tim Southee","BWL",2,7.5,36],
  ["Adam Milne","BWL",1,7.5,33],
  ["Adil Rashid","BWL",2,8.5,37],
  ["Matt Henry","BWL",2,8,33],
  ["Manish Pandey","BAT",7,1,35],
  ["Umesh Yadav","BWL",1,7,37],
  ["Mujeeb Ur Rahman","BWL",1,7.5,24],
];

const SPINNERS = new Set([
  "Mitchell Santner","Karn Sharma","R Ashwin","Noor Ahmad","Ravindra Jadeja",
  "Krunal Pandya","Suyash Sharma","Sunil Narine","Varun Chakravarthy","Adam Zampa",
  "Zeeshan Ansari","Axar Patel","Kuldeep Yadav","Vipraj Nigam","Yuzvendra Chahal",
  "Wanindu Hasaranga","Maheesh Theekshana","Rahul Tewatia","Washington Sundar",
  "Rashid Khan","R Sai Kishore","Ravi Bishnoi","Adil Rashid","Mujeeb Ur Rahman",
  "Sikandar Raza","Liam Livingstone","Glenn Maxwell","Aiden Markram","Deepak Hooda",
  "Riyan Parag","Abhishek Sharma","Harpreet Brar",
]);

const YOUTH_FIRST = ["Arjun","Ravi","Kiran","Vihaan","Aditya","Rohan","Karthik","Ishaan","Dev","Pranav","Sachin","Ankit","Yash","Tanmay","Harsh","Nikhil","Siddharth","Aryan","Kunal","Ved"];
const YOUTH_LAST  = ["Sharma","Patel","Singh","Reddy","Iyer","Kumar","Verma","Rao","Mishra","Chauhan","Gill","Yadav","Desai","Joshi","Kulkarni","Menon","Nair","Pandey","Rathore","Saxena"];

// Media events. fx: fans / trust / tm (whole team morale) / star (star player morale)
const MEDIA = [
  {q:"Pundits say {STAR} is carrying this team alone.",o:[
    {t:"It's a team game",fx:{tm:3,star:-2}},
    {t:"Stars win you titles",fx:{star:6,tm:-2,fans:2}},
    {t:"No comment",fx:{fans:-2}}]},
  {q:"A journalist questions your team selection.",o:[
    {t:"I pick on form",fx:{tm:2,trust:2}},
    {t:"Mind your own business",fx:{fans:-3,trust:-2,tm:3}},
    {t:"Fair point, we'll review",fx:{trust:3,tm:-2}}]},
  {q:"The owner wants flashier cricket to sell tickets.",o:[
    {t:"Winning sells tickets",fx:{trust:-3,tm:3}},
    {t:"You got it, boss",fx:{trust:5,fans:3,tm:-2}},
    {t:"We'll find a balance",fx:{trust:2,fans:1}}]},
  {q:"{STAR} skipped a sponsor event to hit the nets.",o:[
    {t:"Cricket comes first",fx:{star:5,trust:-3}},
    {t:"Fine him",fx:{star:-6,trust:4}},
    {t:"Smooth it over",fx:{trust:1,star:1}}]},
  {q:"Fans are chanting your name outside the stadium!",o:[
    {t:"I love this city",fx:{fans:5}},
    {t:"Credit to the players",fx:{tm:4}},
    {t:"Wait till we win the title",fx:{fans:2,trust:2}}]},
  {q:"A rival coach called your tactics 'stone age'.",o:[
    {t:"Scoreboard talks",fx:{fans:3,tm:2}},
    {t:"He's right, we'll modernise",fx:{trust:2,tm:-3}},
    {t:"Ignore it",fx:{tm:1}}]},
  {q:"Reports of a dressing-room argument are leaking.",o:[
    {t:"Deny everything",fx:{fans:-2,tm:1}},
    {t:"We sorted it in-house",fx:{tm:3}},
    {t:"Name and shame",fx:{tm:-5,trust:2,fans:2}}]},
  {q:"A young fan asks if you'll win the cup this year.",o:[
    {t:"Promise them the trophy",fx:{fans:5,trust:-2}},
    {t:"We'll fight for every run",fx:{fans:2,tm:2}},
    {t:"Make no promises",fx:{trust:1}}]},
  {q:"{STAR}'s agent hints at wanting a bigger contract.",o:[
    {t:"We'll talk at season end",fx:{star:-2,trust:1}},
    {t:"Nobody is bigger than the club",fx:{star:-5,tm:2,trust:2}},
    {t:"He's worth every rupee",fx:{star:5,trust:-2}}]},
  {q:"TV wants you on a celebrity cooking show.",o:[
    {t:"Do it for the fans",fx:{fans:5,trust:-2}},
    {t:"Focus on cricket",fx:{trust:3}},
    {t:"Send {STAR} instead",fx:{star:3,fans:2}}]},
];
